### ISSUE TITLE
Override environment variable

### ISSUE THREAD

**Issue by sysmat** [payara/docker-payaraserver-full#15]
I'm trying to override user&password with compose, but with no luck, payara is up but  authentication failed
my docker-compose.yml:

```yml
version: '2.0'

services:
  payara41:
    image: zelenjak.arnes.si:5000/payara/server-full
    environment:
      - ADMIN_USER myuser
      - ADMIN_PASSWORD mypass
      - PAYARA_DOMAIN payaradomain
    ports:
      - 4848:4848
      - 8009:8009
      - 8080:8080
      - 8181:8181
  ```
 
Is this possible or I'm doing something wrong

Regards, Tomaž

**Comment by mikecroft** [comment]
This won't work because you're setting these environment variables after the Docker image has already been built.

An alternative option is to clone this repo and modify the environment variables yourself. You can then either build this image from within Docker Compose, or build it separately and upload it to your own docker registry (or even your own Docker Hub account, though that would not be advisable if the reason for this is to use your own passwords).

For example, if you create a new Dockerfile in a directory in the same location as your `docker-compose.yml`, (`my-payara-server-full/Dockerfile`) you could use the `build` property, rather than the `image` property.

```yaml
  payara-full:
    build: ./my-payara-server-full
    ports:
      - 4848:4848
      - 8009:8009
      - 8080:8080
      - 8181:8181
```
